[build]
target-dir = "target"

[target.aarch64-linux-android]
linker = "aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
linker = "armv7-linux-androideabi-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android-clang"

[target.i686-linux-android]
linker = "i686-linux-android-clang"
